export const actionTypes = {
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    ERROR_GAME_NOT_CREATED: 'ERROR_GAME_NOT_CREATED',
    ERROR_GAME_NOT_JOINED: 'ERROR_GAME_NOT_JOINED',
    ERROR_GAME_NOT_STARTED: 'ERROR_GAME_NOT_STARTED',
    ERROR_ANSWER_NOT_UPDATED: 'ERROR_ANSWER_NOT_UPDATED',
    SET_COMPONENT_TO_RENDER: 'SET_COMPONENT_TO_RENDER',
    CREATE_AND_JOIN_GAME: 'CREATE_AND_JOIN_GAME',
    JOIN_GAME: 'JOIN_GAME',
    ANSWER: 'ANSWER',
}
